import Head from "next/head";
import Image from "next/image";
import Center from "../components/Center";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div className="bg-black h-screen overflow-hidden">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>SONO</title>
      </Head>

      <main className="flex">
        <Sidebar />
        <Center />
      </main>

      <div>
        {/* {player} */}
      </div>
    </div>
  );
}
