import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>SONO</title>
      </Head>

      <main>
        {/* side bar */}
        {/* {center} */}
      </main>

      <div>
        {/* {player} */}
      </div>
      <h1>Sono</h1>
    </>
  );
}
